name: 🚀 Check and Deploy Swag App

on:
  push:
    branches:
      - "main"
  # PRs trigger checks, but no deploy
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: ⬣ Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Run Tests
        run: deno task test

  publish:
    # Only publish on main branch pushes, not as part of a PR
    if: ${{ !github.event.pull_request }}
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: 🛠 Build & Deploy
        run: |
          deno task install
          deno task build
          cd scripts
          yarn
          yarn deploy
        env:
          ARNS: ${{ secrets.ARNS }}
